# Generated by Django 5.2.15 on 2026-07-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('csv_file', models.FileField(upload_to='datasets/')),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
    ]
