# Generated by Django 5.2.15 on 2026-07-05 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.CharField(max_length=30)),
                ('stock_code', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('invoice_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_id', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_sales', to='data_ingestion.dataset')),
            ],
            options={
                'db_table': 'raw_sales',
                'indexes': [models.Index(fields=['invoice'], name='raw_sales_invoice_ef40f2_idx'), models.Index(fields=['stock_code'], name='raw_sales_stock_c_20a606_idx'), models.Index(fields=['invoice_date'], name='raw_sales_invoice_98e3a9_idx')],
            },
        ),
    ]
