# Generated by Django 5.2.15 on 2026-07-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['email'], name='customers_email_92e882_idx')],
            },
        ),
    ]
