# Generated by Django 5.2.15 on 2026-07-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='reorder_level',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='current_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
